//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vprpr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// New class2.
    /// </summary>
    // *** Start programmer edit section *** (NewClass2 CustomAttributes)

    // *** End programmer edit section *** (NewClass2 CustomAttributes)
    [AutoAltered()]
    [Caption("New class2")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("NewClass2E", new string[] {
            "Должность as \'Должность\'",
            "Должность.Имя as \'Имя\'"}, Hidden=new string[] {
            "Должность.Имя"})]
    [MasterViewDefineAttribute("NewClass2E", "Должность", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Имя")]
    [View("NewClass2L", new string[] {
            "Должность.Имя as \'Имя\'"})]
    public class NewClass2 : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Vprpr.Должность fДолжность;
        
        // *** Start programmer edit section *** (NewClass2 CustomMembers)

        // *** End programmer edit section *** (NewClass2 CustomMembers)

        
        /// <summary>
        /// New class2.
        /// </summary>
        // *** Start programmer edit section *** (NewClass2.Должность CustomAttributes)

        // *** End programmer edit section *** (NewClass2.Должность CustomAttributes)
        [PropertyStorage(new string[] {
                "Должность"})]
        [NotNull()]
        public virtual IIS.Vprpr.Должность Должность
        {
            get
            {
                // *** Start programmer edit section *** (NewClass2.Должность Get start)

                // *** End programmer edit section *** (NewClass2.Должность Get start)
                IIS.Vprpr.Должность result = this.fДолжность;
                // *** Start programmer edit section *** (NewClass2.Должность Get end)

                // *** End programmer edit section *** (NewClass2.Должность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (NewClass2.Должность Set start)

                // *** End programmer edit section *** (NewClass2.Должность Set start)
                this.fДолжность = value;
                // *** Start programmer edit section *** (NewClass2.Должность Set end)

                // *** End programmer edit section *** (NewClass2.Должность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "NewClass2E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass2E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass2E", typeof(IIS.Vprpr.NewClass2));
                }
            }
            
            /// <summary>
            /// "NewClass2L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View NewClass2L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("NewClass2L", typeof(IIS.Vprpr.NewClass2));
                }
            }
        }
    }
}
