//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vprpr
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должность.
    /// </summary>
    // *** Start programmer edit section *** (Должность CustomAttributes)

    // *** End programmer edit section *** (Должность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностьE", new string[] {
            "Имя as \'Имя\'"})]
    [View("ДолжностьL", new string[] {
            "Имя as \'Имя\'"})]
    public class Должность : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмя;
        
        // *** Start programmer edit section *** (Должность CustomMembers)

        // *** End programmer edit section *** (Должность CustomMembers)

        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (Должность.Имя CustomAttributes)

        // *** End programmer edit section *** (Должность.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (Должность.Имя Get start)

                // *** End programmer edit section *** (Должность.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (Должность.Имя Get end)

                // *** End programmer edit section *** (Должность.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должность.Имя Set start)

                // *** End programmer edit section *** (Должность.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (Должность.Имя Set end)

                // *** End programmer edit section *** (Должность.Имя Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьE", typeof(IIS.Vprpr.Должность));
                }
            }
            
            /// <summary>
            /// "ДолжностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностьL", typeof(IIS.Vprpr.Должность));
                }
            }
        }
    }
}
